language: csharp
solution: AdvanceDLSupport.sln
os:
  - linux
  - osx
matrix:
  include:
    - mono: latest
      dotnet: 2.1.3
before_install:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
install:
  - dotnet restore
script:
  - msbuild /p:Configuration=Debug AdvanceDLSupport.sln
  - dotnet test AdvancedDLSupport.Tests --no-build
  - dotnet test Mono.DllMap.Tests --no-build