image: Visual Studio 2017
init:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
configuration: Debug
before_build:
  - dotnet restore
build:
  parallel: true
  project: AdvanceDLSupport.sln
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
test:
  assemblies:
    only:
      - AdvancedDLSupport.Tests.dll
      - Mono.DllMap.Tests.dll