image: Visual Studio 2017
init:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
configuration: Debug
build:
  parallel: true
  project: AdvanceDLSupport.sln
test:
  assemblies:
    only:
      - AdvancedDLSupport.Tests.dll
      - Mono.DllMap.Tests.dll